# 构建、测试并发布2.x分支

name: Publish 2.x to npm

on:
  push:
    tags:
      - v2.*

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - run: npm test
      - run: npm publish --tag second --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
